/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AbstractRoyalties,
  AbstractRoyaltiesInterface,
} from "../AbstractRoyalties";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "royalties",
    outputs: [
      {
        internalType: "address payable",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "value",
        type: "uint96",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AbstractRoyalties__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractRoyaltiesInterface {
    return new utils.Interface(_abi) as AbstractRoyaltiesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbstractRoyalties {
    return new Contract(address, _abi, signerOrProvider) as AbstractRoyalties;
  }
}
